### ISSUE TITLE
Test that only users with site admin privileges can access CSS Editor

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSSEditor#4]
Only users with site administrator privileges/roles can:
* see CSS Editor in the site context menu,
* have access to the form at the following route: `admin/site/s/{site-slug}/css-editor/index`. (Users without access that go to the route should see a `PermissionDeniedException`.)

**Comment by mebrett** [comment]
Can confirm that Editor and Author users do not see the CSS editor page unless they have Admin privileges on the site (Editor and Viewer do not). 

Anyone with Global or Site Admin privileges can edit the CSS on a site, regardless of whether they've been added to that site as a user.

```
Omeka\Mvc\Exception\PermissionDeniedException: User does not have permission to edit CSS in /var/www/html/mebrett/testomekas/modules/CSSEditor/src/Controller/Admin/IndexController.php:15
Stack trace:
#0 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): CSSEditor\Controller\Admin\IndexController->indexAction()
#1 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#2 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#3 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#4 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#5 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/html/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#9 {main}
```
